apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "call-nested" (list . "prosody" "prosody.fullname") }}-common
  labels:
    {{- include "jitsi-meet.labels" . | nindent 4 }}
data:
  {{- if .Values.enableAuth }}
  ENABLE_AUTH: "1"
  {{- else }}
  ENABLE_AUTH: "0"
  {{- end }}
  {{- if .Values.enableGuests }}
  ENABLE_GUESTS: "1"
  {{- else }}
  ENABLE_GUESTS: "0"
  {{- end }}
  XMPP_DOMAIN: {{ include "jitsi-meet.xmpp.domain" . }}
  XMPP_MUC_DOMAIN: {{ .Values.xmpp.muxDomain | default (printf "muc.%s" (include "jitsi-meet.xmpp.domain" .)) }}
  XMPP_AUTH_DOMAIN: {{ .Values.xmpp.authDomain | default (printf "auth.%s" (include "jitsi-meet.xmpp.domain" .)) }}
  XMPP_GUEST_DOMAIN: {{ .Values.xmpp.guestDomain | default (printf "guest.%s" (include "jitsi-meet.xmpp.domain" .)) }}
  XMPP_RECORDER_DOMAIN: {{ .Values.xmpp.recorderDomain | default (printf "recorder.%s" (include "jitsi-meet.xmpp.domain" .)) }}
  XMPP_INTERNAL_MUC_DOMAIN: {{ .Values.xmpp.internalMucDomain | default (printf "internal-muc.%s" (include "jitsi-meet.xmpp.domain" .)) }}
  TZ: '{{ .Values.tz }}'
  {{- range $key, $value := .Values.extraCommonEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
