apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jitsi-meet.web.fullname" . }}
  labels:
    {{- include "jitsi-meet.web.labels" . | nindent 4 }}
data:
  DISABLE_HTTPS: '{{ .Values.web.httpsEnabled }}'
  ENABLE_HTTP_REDIRECT: '{{ .Values.web.httpRedirect }}'
  JICOFO_AUTH_USER: '{{ .Values.jicofo.xmpp.user }}'
  XMPP_BOSH_URL_BASE: 'http://{{ include "jitsi-meet.xmpp.server" . }}:{{ index .Values.prosody.service.ports "bosh-insecure" }}'
  {{- range $key, $value := .Values.web.extraEnvs }}
  {{- if not (kindIs "invalid" $value) }}
  {{ $key }}: {{ tpl $value $ | quote }}
  {{- end }}
  {{- end }}
